### ISSUE TITLE
I can't use help documents,when I press "F1" or load examples,Qt Creator will be closed directly

### ISSUE THREAD

**Issue by stephenxin** [ros-industrial/ros_qtc_plugin#277] opened 2018-05-16 12:57 UTC
ros_qtc_plugin is very nice,but I can't use help documents,when I press "F1" or load examples,the Qt Creator with ROS Plug-in will be closed directly.I guess it's something wrong with path.I tried,but I still don't know how to do,can anyone help,thanks.
ps: another qt creator works properly.

**Comment by Levi-Armstrong** [comment] 2018-05-17 02:15
I will take a look, I am able to recreate the issue.

**Comment by stephenxin** [comment] 2018-05-25 12:44
hello，have you solved the issue?thanks.@Levi-Armstrong

**Comment by Levi-Armstrong** [comment] 2018-06-14 18:16
I have not. I am working on the next release which will have this issue resolved.

**Comment by svavs** [comment] 2018-11-09 15:00
Seems a Duplicate of #289

**Comment by Levi-Armstrong** [comment] 2018-11-28 14:53
This is fixed in the latest version. See wiki to download the latest installer.

**Closed by Levi-Armstrong** 2018-11-28 14:53 UTC
Labels: wrid18
