### ISSUE TITLE
Help: Cannot retrieve remote tree while installation

### ISSUE THREAD

**Issue by Salman-F** [ros-industrial/ros_qtc_plugin#465] opened 2022-07-28 18:12 UTC
Hello,

i want to install qtcreator with ros plugin.
But i get the error message "Cannot retrieve remote tree".

I think the server is available so i dont know what the problem is.

I am on Ubunut 20.04 (frehsly installed)

I also tried setting a temporary repository with the path to: https://qtcreator-ros.datasys.swri.edu/downloads/repositories/bionic/latest/

But i get this error code: Cannot open Updates.xml for reading: No file name specified

I got this information from #303

I just tried installing it with: `sudo snap install qtcreator-ros --classic` but the application doesn't open :(

After trying to start qtcreator installed via snap i get this error message

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

I tried the offline installer: https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html
But the qt creator version is really old and doesnt include examples or anything...
What is the correct way to install qt creator with ros?

**Comment by christian-rauch** [comment] 2022-07-28 19:51
Can you be more specific what you are trying to do? Do you have issues to download the git repo or the snap package?

**Comment by Salman-F** [comment] 2022-07-28 19:55
@christian-rauch 
Hello, i documented everythin i tried.
I am trying to install qt creator with ros plugin. 
I tried
1) The online installer found [here](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html)
2) after that i tried the snap package and this did not work either
3) after that i installed the offline installer [here](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html) --> but this versions seems old and it looks like it is not the right way to install

All errors accurd are mentioned above.
What do you mean with "do you have issues downloading the git repo"?

I just want to install qtcreator with ros for a university project. I dont care on which way haha

**Comment by christian-rauch** [comment] 2022-07-28 20:01
> What do you mean with "do you have issues downloading the git repo"?

When you said
> i want to install qtcreator with ros plugin.

it wasn't clear to me how you tried to install it. There are multiple ways. I assumed that `Cannot retrieve remote tree` was related to the git remote tree.

The recommended (and easiest) way is now the snap package. But I see just now that it does not work properly with the platform plugins.

Alternatively, you can follow the [Plugin Installation instructions](https://github.com/ros-industrial/ros_qtc_plugin#plugin-installation) and install the plugin on top of a regular Qt Creator installation.

**Comment by Salman-F** [comment] 2022-07-28 20:06
I got this message `Cannot retrieve remote tree` from the online installer found in the documentation [here](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html) (for bionic 18.04) -> I also tried everythin mentioned in #303

Sadly the easiest way doesn't work :( 

Okay i will try to install the plugin on top of a regular Qt Creator installation. Do i have to execute the [Build](https://github.com/ros-industrial/ros_qtc_plugin#build) section too?

And thank you very much for your fast help

**Comment by christian-rauch** [comment] 2022-07-28 20:19
I think the online installer is deprecated. I haven't used either of those in a long time since they install a very old Qt Creator version.

> Sadly the easiest way doesn't work :(

I reverted that change to an older version (Qt Creator 7). If you delete the snap and install again, it should install the previous version on the stable channel with Qt Creator 7. The new version will stay on the edge channel until I managed to fix that issue.

**Comment by Salman-F** [comment] 2022-07-28 21:43
Okay.
I just tried to install the Plugin on top of a regular Qt Creator installation.
All seemed well but unfortunately i can't build my projects.
I get the following message (in the tab general message)
```
[ROS Error] ROS does not appear to be installed.
 Check ROS Settings page to verify that the install location is valid 
```
And this error message

```
23:41:18: Could not start process "colcon" build --cmake-args -G 'CodeBlocks - Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug.
Error while building/deploying project test (kit: Desktop)
When executing step "Colcon Step"
```

I think it appears because i cant set my Default Distribution.

![Screenshot from 2022-07-28 23-39-00](https://user-images.githubusercontent.com/64493622/181642272-d610f445-209c-44e7-b25b-fcaff8a69890.png)

If i press the Drop down menu nothing appears. This is Qt Creator 8.0.0.

Any suggestions why this happens?

**Comment by christian-rauch** [comment] 2022-07-28 21:46
1. Can you build the workspace from the terminal?
2. Does the file `/usr/bin/colcon` exist?

**Comment by Salman-F** [comment] 2022-07-28 22:01
1. Yes i can build from the terminal
2. Yes the file `/usr/bin/colcon` exist

After i build from the terminal i could also build in qt creator.
I tried added a executable to the run configuration and got this error message
![image](https://user-images.githubusercontent.com/64493622/181644627-888ce440-4bbc-4ce4-92c5-b31d24002a86.png)

Because of that i tried cleaning the project and again i cant build from qt creator. But if i colcon build from the terminal it works again but the error above occurs.

**Comment by christian-rauch** [comment] 2022-07-28 22:10
Not sure what the problem is here. In any case, this problem is unrelated to the installation the snap and the manual installation should work now.

For the other issue you encounter, check if this is a regression from Qt Creator 7 or earlier by installing those older Qt Creator versions manually and testing with the corresponding plugins from https://github.com/ros-industrial/ros_qtc_plugin/releases.

If this is a regression, please open a new issue related to this specific issue. I am going to close this issue as I consider it fixed. If you still have installation issues, reopen it.

**Closed as completed by christian-rauch** 2022-07-28 22:10 UTC

**Comment by Salman-F** [comment] 2022-07-28 22:43
I personally think it is still an installation issue because i can't get my application running trough qt creator.
I tried executing the executable with a terminal and it worked. I think the red error message above has to do something with the integration of ros in qt creator.

I will try the snap installation later but is their something we could do about Qt Creator 8.0.0 and the ros plugin? Any way to fix it? (so colcon works immediately and you can execute executables)

**Comment by Salman-F** [comment] 2022-07-28 22:51
@christian-rauch i don't think i can reopen this issue by myself

**Comment by christian-rauch** [comment] 2022-07-29 05:51
> I personally think it is still an installation issue because i can't get my application running trough qt creator.
> I tried executing the executable with a terminal and it worked. I think the red error message above has to do something with the integration of ros in qt creator.

The title of this issue does not reflect the problem you are facing. As far as I can tell, you managed to install Qt Creator with plugin.

> I will try the snap installation later but is their something we could do about Qt Creator 8.0.0 and the ros plugin? Any way to fix it? (so colcon works immediately and you can execute executables)

I cannot tell what is wrong in your setup. I cannot reproduce this. It would be better if you provide a full list of steps to reproduce this. From what I can tell from your screenshot is that colcon seems to work but that there are issues writing to a directory.

Qt Creator 8 with plugin works for me on a colcon workspace on ROS2 humble.

**Comment by Salman-F** [comment] 2022-07-29 06:16
Hello
i just tried the snap installation but if i try to execute an executable i get this error:

![image](https://user-images.githubusercontent.com/64493622/181693881-8a42c8cc-85a7-4f2c-b61c-2d913ac268b3.png)

And i am sure that the executable is in that directory.

I will try to get Qt Creator 8 running with the plugin and ROS2 foxy.
The steps i made (maybe you could also post your steps so i can recreate them because it is working for you? @christian-rauch )
1. I installed ROS2 foxy from [here](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html)
2. After that i installed colcon as described on the foxy website [here](https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html#id3)
3. After that i downloaded Qt creator from [here](https://www.qt.io/download-thank-you) (Qt Creator 8.0.0 and Qt 6.3.1)
4. After that i followed the instruction from your installation page [here](https://github.com/ros-industrial/ros_qtc_plugin#plugin-installation)
--> Thats how i got the error in here

> After i build from the terminal i could also build in qt creator. I tried added a executable to the run configuration and got this error message ![image](https://user-images.githubusercontent.com/64493622/181644627-888ce440-4bbc-4ce4-92c5-b31d24002a86.png)
> 
> Because of that i tried cleaning the project and again i cant build from qt creator. But if i colcon build from the terminal it works again but the error above occurs.

I think that maybe i am missing a step or some dependencies because my system is freshly setup -> Ubuntu 20.04

In the general messages tab in Qt Creator i get messages like that
![image](https://user-images.githubusercontent.com/64493622/181695779-fe84307b-cd3c-4548-9d0c-1543ee3dc0bf.png)
I think it is related because i cant set a default distribution

**Comment by jage92** [comment] 2022-11-23 19:01
I have the same issue when I try to run ROS2 node from QtCreator. If I activate the check to run the node in the Linux terminal (in run config panel) not work and QtCreator crash. 

It makes a correct compile of the workspace with Colcon from QtCreator can not run nor debug. 
I am using also Ubuntu 20 with ROS Galactic

**Comment by christian-rauch** [comment] 2022-11-23 20:29
> I have the same issue when I try to run ROS2 node from QtCreator.

Which issue?

> If I activate the check to run the node in the Linux terminal (in run config panel) not work and QtCreator crash.

Can you provide a backtrace or something to reproduce this crash? Is this the snap version or the one from the Qt website?

> It makes a correct compile of the workspace with Colcon from QtCreator can not run nor debug.

You can compile the workspace in Qt Creator but not run it? Can you provide more details what you tried to do?

This issue mentions different settings, e.g. installation with and without the snap. It's difficult to fix the issue if different issues are reported in different configurations.

**Comment by jage92** [comment] 2022-11-24 07:32
You are right, I have opened a new issue. Sorry. The issue is: [#473 ](https://github.com/ros-industrial/ros_qtc_plugin/issues/473)

Best
