### ISSUE TITLE
Add "Setting C++ Code Style" to the FAQ

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#244] opened 2018-02-12 12:51 UTC

**Comment by DavidMerzJr** [comment] 2019-07-03 13:24
@robinsonmm It looks like Levi has merged the PR.  I think this issue should be marked as completed.

**Comment by gavanderhoorn** [comment] 2019-07-03 13:26
It will automatically be moved to the completed column once/if the issue is closed.

**Closed** 2019-07-03 16:49 UTC
Labels: documentation, wrid19
