### ISSUE TITLE
ros-qt include issues

### ISSUE THREAD

**Issue by ROVguy** [ros-industrial/ros_qtc_plugin#382] opened 2019-08-03 16:11 UTC
Hello.
I installed ros-qt using with "qtcreator-ros-bionic-latest-online-installer.run". 
Under "Other projects" there is the "ROS workspace" and I was able to setup a project_ws, package and node. 
To keep things simple I setup a basic node just to test things as I was having issues with an import. When I open the basic node (before or after I build all) qt doesn't recognize any of the ros components as in the attached pic. 

![Screenshot from 2019-08-03 08-47-38](https://user-images.githubusercontent.com/5726985/62414279-461eb080-b5e7-11e9-81e5-fe24cf2c12e0.png)

I can't seem to resolve this with any of the suggestions that I have found.
Any help is greatly appreciated.

**Comment by ghost** [comment] 2019-08-10 12:46
I have a similar problem, the more tricky thing is it works fine on my computer, but doesn't work on another computer

**Comment by Levi-Armstrong** [comment] 2019-08-11 18:11
Can you post the contents of your Henry-ws.workspace file?

**Comment by ghost** [comment] 2019-08-12 15:54
I'm having a similar issue. None of the headers are being parsed. I imported a ROS workspace. Here is my workspace file. I also have a workspace.user file.

The impact is the GUI editor doesnt work. Mainwindow.cpp cant see his header file.. etc.

`<?xml version="1.0"?>
<Workspace>
    <Distribution path="/opt/ros/kinetic"/>
    <DefaultBuildSystem value="1"/>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
</Workspace>`

**Comment by Levi-Armstrong** [comment] 2019-08-12 16:21
Has everything been setup in the CMakeLists.txt and has it built successfully?

**Comment by ghost** [comment] 2019-08-12 16:32
It builds fine. I used catkin_create_qt_pkg to get started hoping it would set everything up. Want to teamviewer into the system? I am not very familiar with CMake.

I tried several clean and builds.

Creds for TV are:
1 356 677 366
6scj79

**Comment by Levi-Armstrong** [comment] 2019-08-12 18:21
I am in a meeting today and tomorrow. But could on Wednesday. One place I would start is by inspecting the code model Tools>C++>Inspect C++ Code Model and make sure it includes your header paths and cpp files are correct for the targets.

**Comment by ROVguy** [comment] 2019-08-13 00:27
@ Levi:
To make life easy I setup a new workspace and project all within QT.
Steps were: 
New Project -> Other Project ->ROS Workspace -> Choose.
Name: qt_setup_test, Location: qt_test.
qt_setup_test (right click and select Build)
Package:
Src (right click and select Add New…) -> Package -> -> choose
Name: qt_test_package -> Next -> Finish
qt_test_package. This was not building or showing up so I closed the WS and reopened it followed by a build. Package was now visible though build devel install and logs are not. (qt_setup_test-1.png)
Added a src folder to qt_test_package and then ran build again

Src in qt_test_package (right click and select Add New…) -> Basic Node -> choose
Name: basic_node_1 -> Next -> Finish (qt_setup_test-2.png)
Src in qt_test_package (right click and select Add New…) -> Basic Publisher Node -> choose
Name: pub_node_1 -> Next -> Finish (qt_setup_test-3.png)
Followed by build once again

On a side note. Things like #include <iostream> don’t work and under tools-options-kits “Imported Kit” has issues. (qt_setup_test-4.png)

Pics are here:
[https://drive.google.com/drive/folders/1wwK-QCkKXOGTmbGfsPgp2c47G4my_gY8?usp=sharing](url)

WS is here:
[https://drive.google.com/file/d/11Zy9luq4mumj7AwF8nPNC_L5jX4KViJ-/view?usp=sharing](url)

**Comment by ROVguy** [comment] 2019-08-13 00:29
> One place I would start is by inspecting the code model Tools>C++>Inspect C++ Code Model and make sure it includes your header paths and cpp files are correct for the targets.
> 
It appears that the Header Paths location is empty.

**Comment by Levi-Armstrong** [comment] 2019-08-18 04:18
Ok I will pull it down and see if I can reproduce the issue.

**Comment by Levi-Armstrong** [comment] 2019-08-18 15:49
I pulled it down.

The first thing, I noticed is I recieved a error message from Qt Creator saying the settings file was created from an older version of Qt Creator. Can you post the versions you are currently using under Help->About Qt Creator?

Also, it does not find headers because in this example there is no targets that use any of the cpp files in your workspace. If you create targets in the CMakeLists.txt file that use the two files then everything works as expected.

**Comment by Levi-Armstrong** [comment] 2019-08-18 15:50
Oh, Also are you building with catkin_make or catkin_tools?

**Comment by ROVguy** [comment] 2019-08-21 11:14
Hello Levi.
Sorry for the delays. Currently traveling for work so replies will be slow.
Qt Creator 4.9.2   Based on Qt 5.12.4 (GCC 7.4.0, 64 bit)

Workspace was set to catkin_tools.

> Also, it does not find headers because in this example there is no targets that use any of the cpp files in your workspace. If you create targets in the CMakeLists.txt file that use the two files then everything works as expected.

> 
I'll try try this today and get bask with results. Thanks

**Comment by ROVguy** [comment] 2019-08-21 16:27
I added a second node that was made just like the first except I chose a basic publisher.
I added these two to CMakeLists.txt the same way as I would when running things out of terminal and still same issues.

**Comment by Levi-Armstrong** [comment] 2019-08-22 14:31
Did you update the workspace where I can pull it down and test it?

**Comment by ROVguy** [comment] 2019-09-09 13:16
> Did you update the workspace where I can pull it down and test it?

Not exactly sure what you mean by that.

**Comment by crisdeodates** [comment] 2021-01-05 15:59
Hi all, is there any progress on this thread? The issue seems to be present still.

**Comment by Levi-Armstrong** [comment] 2021-01-05 16:57
@crisdeodates What issue are you having?

**Comment by christian-rauch** [comment] 2022-03-31 10:26
I am closing this since there have been no new details about the issue or other reports. I've not encountered this issue in newer releases. Please reopen if the problem is persistent.

**Closed as completed by christian-rauch** 2022-03-31 10:26 UTC
