### ISSUE TITLE
no rosrun step ，so can't run node，how can use it

### ISSUE THREAD

**Issue by chang556** [ros-industrial/ros_qtc_plugin#469] opened 2022-10-11 12:47 UTC
![image](https://user-images.githubusercontent.com/75434070/195094427-7fd8ae99-b50e-4a87-b0cf-1aa186b3aa1f.png)

**Comment by christian-rauch** [comment] 2022-10-11 13:35
Duplicate of #459.

**Closed as completed by christian-rauch** 2022-10-11 13:35 UTC
