### ISSUE TITLE
Ros Debug  Sourced workspace

### ISSUE THREAD

**Issue by lianbashou123** [ros-industrial/ros_qtc_plugin#437] opened 2021-09-08 14:24 UTC
![20210908_201834](https://user-images.githubusercontent.com/88788972/132527402-f06bf627-452d-49cd-8fc7-0d97b05b6e96.jpg)
how to add  ros debug  sourced workspace  or  how  to  deal this problem

**Comment by christian-rauch** [comment] 2021-09-08 14:27
Can you specify what the problem is? After loading a workspace, you can use Qt Creator as usual to debug executables with gdb.

**Comment by lianbashou123** [comment] 2021-09-08 14:44
Because I'm a beginner and just learned QT ROS, I wrote a hello project today. I don't know whether to add environment variables. Hello should be displayed when running, but the following is always displayed  Ros debug sourced ……

**Comment by christian-rauch** [comment] 2021-09-08 14:49
If you just try to compile a pure qmake or CMake project, then you actually do not need the ROS plugin. The plugin is only required for catkin/colcon workspaces.

Regarding your Qt project, you haven't provided sufficient information to give advice. It's not even clear what the problem is or what you want to achieve. If you want to learn how to create a Qt program from scratch, then a good start may be: https://doc.qt.io/qt-5/cmake-get-started.html.

**Comment by lianbashou123** [comment] 2021-09-08 16:12
I have a question. Can QT ROS generate Linux apps？

**Comment by christian-rauch** [comment] 2021-09-08 16:17
Yes, of course. You can generate Linux programs with Qt and/or the ROS framework. I still don't see how this is related to the ROS plugin here. If you want to create a Qt program on Linux, I recommend that you follow the link that I posted previously. For ROS, you can follow the official tutorials http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber(c++).

I am going to close this issue since I believe your question is not related to the ROS Qt Creator plugin. If you have an issue that is specific to the plugin, then please open a new issue a be specific about the issue.

**Closed as completed by christian-rauch** 2021-09-08 16:17 UTC

**Comment by lianbashou123** [comment] 2021-09-08 16:29
I want to be a UAV Ground Station recently, but our UAV is realized through mavros through TX 2 and Px4 offline offboard mode. Therefore, I want to use QT as a ground station that can communicate with ROS command frame, not QT ground station through protocol serial port in the past

**Comment by christian-rauch** [comment] 2021-09-08 16:32
Sorry, but this is not the right place to ask UAV or PX4 related questions. This project only deals with the ROS integration into Qt Creator. For questions or bug reports specific to other projects, please use their dedicated issue tracker or forums.

**Comment by lianbashou123** [comment] 2021-09-08 16:44
thank you very much
