### ISSUE TITLE
After latest update Qt Creator ROS plugin won't compile any more

### ISSUE THREAD

**Issue by iminternet** [ros-industrial/ros_qtc_plugin#73] opened 2017-01-16 12:25 UTC
Hey,
I just upgraded qt57creator-plugin-ros:amd64 from 0.1.3-0trusty2 to 0.1.4-0trusty4 with apt.
I closed my qt creator 57 session before. Everything was working fine till then. Qt Creator found my workspace and saved all paths in the catkin.workspace file.

After the upgrade qt creator won't find any libs or included files. (See pic, all red underlined files or libs cant be found).
![missing_libs](https://cloud.githubusercontent.com/assets/24550050/21982957/052d60c8-dbef-11e6-8bb3-eed44a0feaa4.jpg)

I tried to import the catkin workspace again, so your plugin exchanged the workspace file with paths to a one without any paths:
`<?xml version="1.0"?>
<Workspace>
    <Distribution name="indigo"/>
    <DefaultBuildSystem value="0"/>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
</Workspace>`
Compiling doesn't work anymore too. Nothing happens, no error messages whatsoever.

What needs to be done to make your QtCreator57 work again?

Thanks in advance :)

**Comment by Levi-Armstrong** [comment] 2017-01-16 14:56
What is printed out in the Qt Creator Compiler Output window?

**Comment by iminternet** [comment] 2017-01-16 16:23
When I start your qtcreator with the .desktop file how its adviced in your wiki:
I press Ctrl + B / or "Build Project {projectname}" but really nothing happens. The compiler output is blank space.

If I start your qtcreator from terminal (I inserted the qt57.env in .bashrc) then a line
`"Unable to locate build information for package: ros_service_examples"`
appears, when I try to import the old ROS workspace.
(ros_service_examples is one project from the offical ROS tutorials and was working).

And again, the import was working before the last update.
I will try to get your new update now :)

**Comment by Levi-Armstrong** [comment] 2017-01-16 17:40
@iminternet, Sorry about the issue. I found two bugs which have been corrected. You should be able to update in about 10 minutes. Let me know if the issue is resolved.

**Comment by Levi-Armstrong** [comment] 2017-01-16 17:45
@iminternet, it looks like it has been published.

**Comment by iminternet** [comment] 2017-01-16 18:18
I did update, but it did not solve the problem :(
I deleted the catkin.workspace in my catkin workspace and tried to import the ROS Workspace again from the start. The new catkin.workspace still looks like this:
`
<?xml version="1.0"?>
<Workspace>
    <Distribution name="indigo"/>
    <DefaultBuildSystem value="0"/>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
</Workspace>
`
I did also try to get an old catkin.workspace from a backup, but it did not help. All directories were set in this older catkin.workspace, but all the QWidget etc includes are still "missing" ("No such file or directory").

**Comment by AndreaLampart** [comment] 2017-01-16 18:35
Today, my unity crashed and after some difficult workarounds I managed to get it running again. I had similar problems like you, but it showed that it only reset some options. You should again add the Build steps like in the documentation of this plugin. Then the build button should work again. What I have lost and cannot find anymore is the option to "Reload missing include directories".

**Comment by Levi-Armstrong** [comment] 2017-01-16 18:59
@AndreaLampart; The "Reload missing include directories" has been removed. The code model is updated every time the project is built if needed.

Also sorry about the build option getting lost. I had to change a lot of the internals to allow multiple build systems.

**Comment by Levi-Armstrong** [comment] 2017-01-16 19:03
@iminternet, The default build step has been removed. Where you able to get everything to build when setting up the build step again?

**Comment by AndreaLampart** [comment] 2017-01-16 20:05
@Levi-Armstrong Thanks for clarifying this! And really thanks for your support! The plugin is great!

**Comment by Levi-Armstrong** [comment] 2017-01-16 20:38
@AndreaLampart and @iminternet, I just pushed another update where dynamic libraries where not being loaded into the code model. It should be published in about 15 minutes.

**Comment by AndreaLampart** [comment] 2017-01-17 08:48
@Levi-Armstrong I checked the updated version today. The problem is that even after building it doesn't find missing include directories, whereas earlier the "Reload missing include directories" step always resolved the problem.

**Comment by iminternet** [comment] 2017-01-17 12:18
@AndreaLampart I created a new workspace after the update, copied my package in src to the new workspace and deleted all the files in all package folders which were new / made by the ROS Plugin.

Then I did the import again and it did not find the missing includes. Despite this I hit "Build Project" and it was working, all the missing includes and libs were found.

I dont know why it doesnt find them from the start on, after the new import, but now its working, I guess.

**Comment by AndreaLampart** [comment] 2017-01-17 12:31
@iminternet Thanks, that fully resolved the problem! Obviously the workspace is not upwards compatible. I now also created a new workspace (purging of old not needed though). It now resolves all includes at creation. I guess this issue is hereby solved atm and can be closed. Thanks to @iminternet  and @Levi-Armstrong !

**Comment by AndreaLampart** [comment] 2017-01-17 13:19
Ok sry to write that, case not closed. After restarting qt creator , it again looses all dependencies. Also, the build environment is not set correctly. It's missing all Catkin paths. At Run configuration I could not set any launch files. And build configuration catkin_make -DCMAKE_BUILD_TYPE=RelWithDebInfo cannot be deployed (probably because of the wrong environment)

**Comment by iminternet** [comment] 2017-01-17 14:40
I was wondering yesterday cause I had the same problem.
I did also loose all the catkin dependencies, but setting up a new catkin workspace, sourcing the new devel/setup.bash, copied my package in src, cleaning the folders (everything done in terminal) and then importing the new ROS Workspace in qtcreator solved it for me.
I dont know why you are loosing these dependencies again after you restart qtcreator.

In my new .workspace /or .workspace.user file in the workspace main folder are still no paths writen.

**Comment by AndreaLampart** [comment] 2017-01-17 14:54
I agree. Also in my .workspace file are no listed dependencies altough the rest seems to work now with the earlier described changes. I have to correct my statement: I lost the dependencies after rebooting ubuntu. At the moment everything runs fine. I'll keep you updated.

**Comment by Levi-Armstrong** [comment] 2017-01-17 15:19
How the code model works:

Currently the project depend on the generation of a Code Blocks project file which gets generated from cmake when the project is built. So everytime you build the project it should generate new Code Blocks files for each package. You check in the build directory for the package and there should be a .cbp file.

**Comment by Levi-Armstrong** [comment] 2017-01-17 15:23
@iminternet and @AndreaLampart 

>In my new .workspace or .workspace.user file in the workspace main folder are still no paths writen.

The include paths being written to the .workspace file was a temparary solution because all include are already located in the Code Blocks project file. The previous "Reload missing include directories" would just parse the Code Blocks project file, but now this is done automatically after every build.

**Comment by Levi-Armstrong** [comment] 2017-01-17 15:28
@iminternet and @AndreaLampart: Thank you for your feedback and patience. What remaining issues are you having?

**Comment by Jmeyer1292** [comment] 2017-01-18 01:33
Out of curiosity, would it be possible to get a `regenerate code model` button buried somewhere? I often don't build from QtCreator but would like to edit there.

It's not a big deal either way. You should make this plugin function how you would want it to.

**Comment by Levi-Armstrong** [comment] 2017-01-18 16:17
>Out of curiosity, would it be possible to get a regenerate code model button buried somewhere? I often don't build from QtCreator but would like to edit there.

This is a good point. I did not think of this case since I usually build with the editor when using it. I will add the same button back, because it doesn't hurt to have it. Also I will look into a way to detect when a build happens outside qtcreator, so it can automatically reload them.

**Comment by Levi-Armstrong** [comment] 2017-01-18 19:48
@iminternet and @AndreaLampart Are you experiencing any issue, or have they been address with the latest updates?

**Comment by iminternet** [comment] 2017-01-18 19:51
No problems atm, thanks for all your effort.

**Comment by AndreaLampart** [comment] 2017-01-19 00:42
Same for me. Atm works all fine. Thanks!

**Comment by henriqueribeiro** [comment] 2017-01-20 11:12
@Levi-Armstrong, just to clarify, the solution is to import the workspace again?

**Comment by Levi-Armstrong** [comment] 2017-01-20 15:58
@henriqueribeiro I don't think you should not have to with the fixes, but you will have to set up the build configurations again since this has changed to accommodate multiple build system. For each build configuration you will need to make sure to set the correct build system, debug setting and build/clean steps.

**Comment by Levi-Armstrong** [comment] 2017-02-23 14:37
Addressed by issue #81

**Closed by Levi-Armstrong** 2017-02-23 14:37 UTC
Labels: bug
