### ISSUE TITLE
Plugin cannot be loaded

### ISSUE THREAD

**Issue by HowardWhile** [ros-industrial/ros_qtc_plugin#475] opened 2022-12-28 08:13 UTC
Hi there,
When I import the plugin and restart qt creator, I got an error message like this...

![image](https://user-images.githubusercontent.com/18715360/209773960-7fcdec89-36e0-4cc1-beaf-6c1e30d257ae.png)

```
/home/user/.local/share/data/QtProject/qtcreator/plugins/9.0.1/lib/qtcreator/plugins/libROSProjectManager.so: Cannot load library /home/user/.local/share/data/QtProject/qtcreator/plugins/9.0.1/lib/qtcreator/plugins/libROSProjectManager.so: (/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/user/.local/share/data/QtProject/qtcreator/plugins/9.0.1/lib/qtcreator/plugins/libROSProjectManager.so))
```
This is my system infomation
Ubuntu `20.04`
Qt Creator `9.0.1 `
ros_qtc_plugin `9.0`

I have tried below versions and only ros_qtc_plugin 9.0 have problem.
- [x] Qt Creator 6.0.2 + ros_qtc_plugin 0.5.0
- [x] Qt Creator 7.0.2 + ros_qtc_plugin 0.6.0
- [x] Qt Creator 8.0.2 + ros_qtc_plugin 8.1
- [ ] Qt Creator 9.0.1 + ros_qtc_plugin 9.0

Maybe I have to make & install `GLIBC` or update my ubuntu?

**Comment by christian-rauch** [comment] 2022-12-28 11:26
I assume you use the "official" binary distribution of Qt Creator installed by the Qt installer and the plugin from the binary release artefacts?

The problem is here ``version `GLIBC_2.32' not found``, which is probably caused by the different systems where Qt Creator and the plugin are compiled. The binary distribution of the plugin is compiled on `ubuntu-latest`, which is Ubuntu 22.04 at the moment.

I have to look into how to resolve this problem. This is possible since the official binary Qt Creator distribution also works on different Linux distributions.

In the meantime, I suggest you use the [Qt Creator snap package](https://snapcraft.io/qtcreator-ros) which contains Qt Creator and a compatible plugin.

**Comment by HowardWhile** [comment] 2023-01-09 09:32
Thanks for your advice.

Now I use the following environment:
Ubuntu `22.04`
Qt Creator `9.0.1 `
ros_qtc_plugin `9.0`

Can be used normally~

**Comment by christian-rauch** [comment] 2023-01-12 22:17
I downgraded the Ubuntu version in the CI pipeline (https://github.com/ros-industrial/ros_qtc_plugin/pull/477). If you still want to use the latest version from the online installer you can try the [Linux build artefact](https://github.com/ros-industrial/ros_qtc_plugin/suites/10342779782/artifacts/509431062) from that PR.

There will be a new release once this is merged and you will be able to use the official installation instructions again.

**Closed as completed** 2023-01-14 00:53 UTC
